# Generated by Django 3.1.3 on 2022-03-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_customuser_finished_free_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos')),
                ('video_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.classrooms')),
            ],
        ),
    ]
