# Generated by Django 3.1.3 on 2022-03-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_videos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='student_id',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_link',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='appointment',
            name='firstname',
            field=models.CharField(default='None', max_length=250),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lastname',
            field=models.CharField(default='None', max_length=250),
        ),
    ]
