# Generated by Django 3.1.3 on 2022-03-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20220305_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='start_link',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoom_id',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoom_password',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
