# Generated by Django 3.1.3 on 2022-03-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220305_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='start_link',
            field=models.CharField(default='None', max_length=3000),
        ),
    ]
