# Generated by Django 3.1.3 on 2022-03-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220305_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentId',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
