# Generated by Django 3.1.3 on 2022-03-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220305_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignments',
            name='due_time',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
    ]
