# Generated by Django 3.1.3 on 2022-03-06 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220306_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='due_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
