# Generated by Django 3.1.3 on 2022-03-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20220306_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
