# Generated by Django 3.1.3 on 2022-03-08 07:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220308_0728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(default='None', max_length=250)),
                ('lastname', models.CharField(default='None', max_length=250)),
                ('appointment_link', models.CharField(default='None', max_length=250)),
                ('date', models.DateField()),
                ('timing', models.DateTimeField(default=datetime.datetime.now)),
                ('isCancelled', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('reasonOfDisapproval', models.CharField(default='None', max_length=250)),
                ('start_link', models.CharField(default='None', max_length=3000)),
                ('zoom_id', models.CharField(default='None', max_length=20)),
                ('zoom_password', models.CharField(default='None', max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('is_disapproved', models.BooleanField(default=False)),
                ('is_notified', models.BooleanField(default=False)),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.teachers')),
            ],
        ),
    ]
