# Generated by Django 3.1.3 on 2022-03-08 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
