# Generated by Django 3.1.3 on 2022-05-02 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
